### ISSUE TITLE
Move comment feature

### ISSUE THREAD

**Issue by Hari-Bonda** [FriendsOfFlarum/split#36]
as we already know sometimes we are getting errors while merging comments 

split extension is only useful to create new discussion, we can only separate single comment but If we use split to separate the comment and try to merge newly created discussion into different old discussion our merge discussions extension pops out a error.

We need "move single reply" to another discussion feature.

so we can just move the comments to different discussions without splitting or merging.

Once we move single comment from newly created discussion we can manually delete empty discussion 

We request you to bring a "move comment feature" 

https://gvectors.com/wp-content/uploads/2016/03/wpDiscuz-Comment-Frontend-Moderation-move-comment.png

**Comment by rafaucau** [comment]
Moving a comment to another discussion instead of creating a new one is a essential feature. I will try to create a PR at my free time.

**Comment by Hari-Bonda** [comment]
> Moving a comment to another discussion instead of creating a new one is a essential feature. I will try to create a PR at my free time.

if the discussion has no posts please do not permanently delete the discussion because we can not create deleted discussion with the same ID

**Comment by Hari-Bonda** [comment]
Move Posts extension is out.

**Comment by matteocontrini** [comment]
> Move Posts extension is out.

Is it? 🤔

**Comment by Hari-Bonda** [comment]
> > Move Posts extension is out.
> 
> Is it? 🤔
> 
> EDIT: found it https://extiverse.com/extension/sycho/flarum-move-posts

Keep this as secret 😉 we are still testing it.
